name: Draw ZMK keymaps
on:
  workflow_dispatch:
#  push:
#    paths:
#      - "config/*.keymap"
#      - "config/*.dtsi"
#      - "keymap_drawer.config.yaml"
jobs:
  draw:
    uses: Luberry/zmk/.github/workflows/build.yml@pmw3389
    permissions:
      contents: write
    with:
      keymap_patterns: "config/*.keymap"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      parse_args: ""
      draw_args: "charybdis:'-j config/info.json -l default_transform'"
